# Generated by Django 4.1.6 on 2023-04-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='timestamp',
        ),
    ]
