# Generated by Django 4.2 on 2023-05-27 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_contact_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
