# Generated by Django 4.1.6 on 2023-04-09 07:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=100)),
                ('workout_time', models.IntegerField(default=10)),
                ('workouts_type', models.CharField(choices=[('tb', 'Total Body'), ('ub', 'Upper Body'), ('lb', 'Lower Body'), ('cr', 'Core')], default='tb', max_length=2)),
                ('input_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.ImageField(upload_to='fitness/workouts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkoutCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=40)),
                ('url', models.CharField(max_length=100)),
                ('input_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkoutsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='fitness/post')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.workout')),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='fitness.workoutcategory'),
        ),
    ]
