# Generated by Django 4.1.6 on 2023-04-09 08:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutspost',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
