# Generated by Django 4.1.6 on 2023-04-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_alter_workoutcategory_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutspost',
            name='url',
            field=models.CharField(default='dt', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
