# Generated by Django 4.1.6 on 2023-04-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_workoutspost_url_alter_workout_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='url',
            field=models.CharField(default='title', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='workoutcategory',
            name='url',
            field=models.CharField(default='title', max_length=100, unique=True),
        ),
    ]
