# Generated by Django 4.1.6 on 2023-04-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_alter_workout_url_alter_workoutcategory_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
