# Generated by Django 4.1.6 on 2023-04-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_alter_workout_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutcategory',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
