# Generated by Django 4.1.6 on 2023-04-10 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_alter_workout_workouts_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutspost',
            name='post_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workoutspost',
            name='url',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
