# Generated by Django 4.1.6 on 2023-04-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_workoutspost_post_date_alter_workoutspost_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutspost',
            name='author',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutspost',
            name='url',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workoutspost',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.workout'),
        ),
    ]
