# Generated by Django 4.1.6 on 2023-04-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_workoutspost_sub_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutspost',
            old_name='post_date',
            new_name='publish_date',
        ),
    ]
