# Generated by Django 4.1.6 on 2023-04-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0015_rename_post_date_workoutspost_publish_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutsPost',
            new_name='WorkoutPosts',
        ),
    ]
