# Generated by Django 4.1.6 on 2023-04-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0017_workoutposts_reading_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutPosts',
            new_name='WorkoutPost',
        ),
    ]
