# Generated by Django 4.1.6 on 2023-04-10 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0018_rename_workoutposts_workoutpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutpost',
            name='workout',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.workoutcategory'),
        ),
    ]
