# Generated by Django 4.1.6 on 2023-04-10 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0019_alter_workoutpost_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutpost',
            name='workout',
        ),
        migrations.AddField(
            model_name='workoutpost',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='fitness.workoutcategory'),
        ),
    ]
