# Generated by Django 4.1.6 on 2023-04-10 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0020_remove_workoutpost_workout_workoutpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutpost',
            name='workouts',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='fitness.workout'),
        ),
    ]
