# Generated by Django 4.1.6 on 2023-04-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0022_alter_workoutpost_workouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutpost',
            name='img',
        ),
    ]
