# Generated by Django 4.1.6 on 2023-04-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0023_remove_workoutpost_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutpost',
            name='sub_description',
        ),
    ]
