# Generated by Django 4.1.6 on 2023-04-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0024_remove_workoutpost_sub_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='url',
            new_name='workout_url',
        ),
        migrations.RenameField(
            model_name='workoutpost',
            old_name='url',
            new_name='post_url',
        ),
    ]
