# Generated by Django 4.1.6 on 2023-04-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0025_rename_url_workout_workout_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='workout_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='workoutpost',
            old_name='post_url',
            new_name='url',
        ),
    ]
