# Generated by Django 4.1.6 on 2023-04-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0026_rename_workout_url_workout_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutpost',
            name='workouts',
        ),
    ]
