# Generated by Django 4.1.6 on 2023-04-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0028_workoutpost_workouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='url',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutcategory',
            name='url',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutpost',
            name='url',
            field=models.SlugField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
