# Generated by Django 4.2 on 2023-04-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0029_alter_workout_url_alter_workoutcategory_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutpost',
            name='title',
        ),
    ]
