# Generated by Django 4.2 on 2023-04-25 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0030_remove_workoutpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutpost',
            name='workouts',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='fitness.workout'),
            preserve_default=False,
        ),
    ]
