# Generated by Django 4.1.6 on 2023-04-15 16:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_title', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=100)),
                ('img', models.ImageField(upload_to='nutrition/categories')),
                ('sub_cat', models.CharField(choices=[('ex', 'Explore'), ('lh', 'Living Healthy')], default='ex', max_length=2)),
                ('cat_url', models.SlugField(blank=True, max_length=100)),
                ('input_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sub_description', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('post_url', models.SlugField(blank=True, max_length=200)),
                ('img', models.ImageField(upload_to='nutrition/posts')),
                ('tags', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('input_date', models.DateField(default=django.utils.timezone.now)),
                ('reading_time', models.IntegerField(default=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='nutrition.nutritioncategory')),
            ],
        ),
    ]
