# Generated by Django 4.1.6 on 2023-04-10 08:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=100)),
                ('home_img', models.ImageField(upload_to='health/homecontext')),
                ('img', models.ImageField(upload_to='health/categories')),
                ('url', models.SlugField(max_length=100, unique=True)),
                ('input_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HealthPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sub_description', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('url', models.SlugField(max_length=200, unique=True)),
                ('img', models.ImageField(upload_to='health/posts')),
                ('topics', models.CharField(default='', max_length=100)),
                ('input_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='health.healthcategory')),
            ],
        ),
    ]
