# Generated by Django 4.1.6 on 2023-04-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_rename_heading_healthcategory_cat_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcategory',
            name='sub_cat',
            field=models.CharField(choices=[('ex', 'Explore'), ('hc', 'Health Condition')], default='ex', max_length=5),
        ),
    ]
