# Generated by Django 4.1.6 on 2023-04-11 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_remove_healthcategory_home_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpost',
            name='input_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
