# Generated by Django 4.1.6 on 2023-04-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_alter_healthpost_input_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpost',
            name='url',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
