# Generated by Django 4.1.6 on 2023-04-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_alter_healthpost_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcategory',
            old_name='url',
            new_name='cat_url',
        ),
        migrations.RenameField(
            model_name='healthpost',
            old_name='url',
            new_name='post_url',
        ),
    ]
