# Generated by Django 4.1.6 on 2023-04-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_rename_url_healthcategory_cat_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthpost',
            name='reading_time',
            field=models.IntegerField(default=10),
        ),
    ]
