# Generated by Django 4.1.6 on 2023-04-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_healthpost_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcategory',
            name='cat_url',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
