# Generated by Django 4.1.6 on 2023-04-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_alter_healthcategory_cat_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcategory',
            name='sub_cat',
            field=models.CharField(choices=[('ex', 'Explore'), ('hc', 'HealthCondition')], default='ex', max_length=5),
        ),
    ]
