# Generated by Django 4.1.6 on 2023-04-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0013_healthpost_tags_healthpost_views_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='health.tag'),
        ),
    ]
